import Head from 'next/head'
import Layout from './components/Layout'


export default function Home() {
  return (
    
    <Layout>
      <Head>
        <title>A-Bit to Remember</title>
        <meta name="technical blog" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      Hi there, it`s me. Ikhsan ::))
    </Layout>
    
  )
}
