import Head from 'next/head'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>me and next-js</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.text}>
      Hey! welcome to me and next-js!<br/>
      lets see what happens next!
      </div>
    
    </div>
  )
}
